name: Kariton
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  image_picker: ^1.0.0
  smooth_page_indicator: ^1.2.0
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.0.6
  path_provider: ^2.0.11
  url_launcher: ^6.3.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  timezone: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # Latest version at the time of writing

flutter_icons:
  android: true
  ios: true
  image_path: "assets/karitonlogo.png"  # Update this with your icon path

flutter:
  uses-material-design: true
  assets:
    - assets/karitonlogo.png
    - assets/onboard_image.png
    - assets/onboard_image2.png
    - assets/home_background.png
    - assets/profile_icon.png
    - assets/category_0.png
    - assets/category_1.png
    - assets/category_2.png
    - assets/category_3.png
    - assets/profile.png
    - assets/map.png
    - assets/transaction.png
    - assets/guide1.png
    - assets/guide2.png
    - assets/guide3.png
    - assets/guide4.png
    - assets/community.png
    - assets/junkshop.png
    - assets/barangay_icon.png
    - assets/manny_icon.png
    - assets/kanor_icon.png
    - assets/images/avatar.png
    - assets/images/map.jpg
    - assets/images/Vector.png
    - assets/bg.jpg
    - assets/img1.png
    - assets/plastic.png
    - assets/copper.png
    - assets/steel.png
    - assets/karton.png
    - assets/paper.png
    - assets/yero.png
    - assets/profile1.png
    - assets/profile2.png
    - assets/profile3.png
    - assets/profile4.png
    - assets/events.png
    - assets/news.png
    - assets/cash_icon.png
    - assets/goods_icon.png
    - assets/COMMUNITYAA.png
    - assets/JSHOPAAA.png
